# Generated by Django 5.2.4 on 2025-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_remove_aprendiz_programa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aprendiz",
            old_name="teléfono",
            new_name="telefono",
        ),
    ]
