# Generated by Django 5.2.4 on 2025-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_rename_teléfono_aprendiz_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
