# Generated by Django 5.2.4 on 2025-07-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="codigo",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Código del programa"
            ),
        ),
    ]
