# Generated by Django 5.2.4 on 2025-08-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0002_alter_programa_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, unique=True)),
                ('tipo_documento', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('RC', 'Registtro Civil')], default='CC', max_length=10)),
                ('numero_documento', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.IntegerField(max_length=10, unique=True)),
                ('documento_identidad', models.FileField(blank=True, null=True, upload_to='admisiones/documento_identidad/')),
                ('cartificado_academmico', models.FileField(blank=True, null=True, upload_to='admisiones/cartificado_academmico/')),
                ('certificado_eps', models.FileField(blank=True, null=True, upload_to='admisiones/certificado_eps/')),
                ('estado', models.CharField(choices=[('REV', 'En Revisión'), ('ADM', 'Admitido'), ('REC', 'Rechazado')], default='ADM', max_length=3, verbose_name='Estado de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='Programa de Formación')),
            ],
        ),
    ]
