# Generated by Django 5.2.4 on 2025-08-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudadmision',
            old_name='cartificado_academmico',
            new_name='certificado_academmico',
        ),
    ]
