# Generated by Django 5.2.4 on 2025-08-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_rename_cartificado_academmico_solicitudadmision_certificado_academmico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudadmision',
            old_name='certificado_academmico',
            new_name='certificado_academico',
        ),
    ]
